version: '3'
services:
  php:
    build:
      context: ./docker/php
    depends_on:
      - mysql
    volumes:
      - './src:/var/www/html'
  nginx:
    image: nginx:latest
    depends_on:
      - php
    ports:
      - '80:80'
    volumes:
      - './src:/var/www/html'
    configs:
      - source: http_conf
        target: '/etc/nginx/conf.d/default.conf'
  mysql:
    image: mysql:8
    ports:
      - '3306:3306'
    volumes:
      - './docker/volumes/mysql:/var/lib/mysql'
    configs:
      - source: mysql_conf
        target: '/etc/mysql/conf.d/default.conf'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 1
      PMA_PMADB: "phpmyadmin"
      PMA_QUERYHISTORYDB: true
      PMA_HOST: mysql
configs:
  http_conf:
    file: './docker/nginx/conf.d/default.conf'
  mysql_conf:
    file: './docker/mysql/conf.d/default.conf'
