version: '3'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - './src:/var/www/html'
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - './src:/var/www/html'
    configs:
      - source: http_conf
        target: '/etc/nginx/conf.d/default.conf'
  mysql:
    image: mysql:8
    volumes:
      - './docker/volumes/mysql:/var/lib/mysql'

configs:
  http_conf:
    file: './docker/nginx/conf.d/default.conf'